### ISSUE TITLE
max query params $top

### ISSUE THREAD

**Issue by tbugfinder** [CiscoUcs/intersight-ansible#45]
In my case the API only allows max 1000 items instead of 20000.
Anybody else run into such an API error?

https://github.com/CiscoUcs/intersight-ansible/blob/236197d6e3dfba5a61d4dc1e1c73386742352440/library/intersight_facts.py#L88

**Comment by vvb** [comment]
This was recently limited to 1000 on Intersight. Ansible needs to fix this.
